#!/bin/csh
#SBATCH --job-name 1D_S6y1a_Response
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --time=3-16:30:00


setenv OMP_NUM_THREADS 8
setenv MKL_NUM_THREADS 1

setenv WD $SLURM_SUBMIT_DIR

#echo $TMPDIR
#cd $TMPDIR

#cp $WD/run $TMPDIR
#cp $WD/inp* $TMPDIR

time ~/NISE_2017/bin/NISE input1D

#cp *.log $WD
#cp *.dat $WD

